# copy docs from skills-introduction-to-github to skills-introduction-to-github.wiki repo   
name: Copy documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
    copy-docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v4
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                fetch-depth: 0
            - name: debug files and git info
              run: |
                echo "Files in the current directory:"
                ls -R
                echo "present working directory:"
                pwd
                echo "Git info:"
                git config --list
                git status
                git remote -v
                git branch -a
                git log -n 1
                git show --stat