# copy docs from skills-introduction-to-github to skills-introduction-to-github.wiki repo   
name: Copy documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
    copy-docs:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Git repository
            uses: actions/checkout@v4
            with: 
              token: ${{ secrets.GITHUB_TOKEN }}
              fetch-depth: 0
    
          - name: debug files and git info
            run: |
              echo "Files in the current directory:"
              ls -R
              echo "Git info:"
              git config --list
              git status
              git remote -v
              git branch -a
              git log -n 1
              git show --stat
          - name: Clone wiki repository
            env:
              WIKI_REPO: ${{ secrets.WIKI_REPO }}
              WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
            run: |
              git clone https://github.com/Naresh-Shekkari/skills-introduction-to-github.wiki.git wiki
              cd wiki
              echo "Files in the current directory:"
              ls -R
              git config user.name "github-actions"
              echo "Present Working Directory"
              pwd
              echo "Git info:"
              git config --list
              git status
              git remote -v
              git branch -a
              git log -n 1
              git show --stat
          - name: Copy documentation
            run: |
              echo "Copying documentation..."
              cp -r docs/* wiki/
              cd wiki
              echo "Files in the current directory:"
              ls -R
              echo "Copying was successful"
          - name: Commit and push changes
            run: |
              echo "Committing and pushing changes..."
              cd wiki
              echo "Present Working Directory"
              pwd