# copy docs from skills-introduction-to-github to skills-introduction-to-github.wiki repo   
name: Copy documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
    copy-docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Git Wiki repo
              uses: actions/checkout@v4
              with:
                repository: Naresh-Shekkari/skills-introduction-to-github.wiki.git
                token: ${{ secrets.GITHUB_TOKEN }}
                path: skills-introduction-to-github.wiki
                fetch-depth: 0
