# document sync workflow from skills-introduction-to-github to skills-introduction-to-github.wiki repo

name: Sync documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
    copydocs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v4
              with: 
                token: ${{ secrets.GITHUB_TOKEN }}
                fetch-depth: 0

            - name: Checkout skills intro to github repository
              uses: actions/checkout@v4
              with: 
                path: skills-introduction-to-github.wiki
                repository: Naresh-Shekkari/skills-introduction-to-github.wiki.git
                ref: master
                token: ${{ secrets.GITHUB_TOKEN }}
                fetch-depth: 0

            - name: display the files in the repo
              run: |
                echo "Files in the skills-introduction-to-github repo:"
                cd skills-introduction-to-github
                ls -R
